const list = [
  {
    id: 1,
    imageUrl: "/REACT-PIZZA/PizzaImg/image11.png",
    title: "Чизбургер-пицца",
    price: "395",
    types:[0,1],
    sizes: [26, 30, 40],
    category: 0,
  },
  {
    id: 2,
    imageUrl: "/REACT-PIZZA/PizzaImg/image22.png",
    title: "Сырная",
    price: "450",
    types:[0,1],
    sizes: [26, 40],
    category: 1,
  },
  {
    id: 3,
    imageUrl: "/REACT-PIZZA/PizzaImg/image33.png",
    title: "Креветки по-азиатски",
    price: "290",
    types:[0,1],
    sizes: [26, 30, 40],
    category: 2,
  },
  {
    id: 8,
    imageUrl: "/REACT-PIZZA/PizzaImg/image44.png",
    title: "Сырный цыпленок",
    price: "385",
    types:[0,1],
    sizes: [26, 30, 40],
    category: 3,
  },
  {
    id: 1,
    imageUrl: "/REACT-PIZZA/PizzaImg/image11.png",
    title: "Чизбургер-пицца",
    price: "395",
    types:[0,1],
    sizes: [26, 30, 40],
    category: 4,
  },
  {
    id: 6,
    imageUrl: "/REACT-PIZZA/PizzaImg/image22.png",
    title: "Сырная",
    price: "450",
    types:[0,1],
    sizes: [26, 30, 40],
    category: 5,
  },
  {
    id: 7,
    imageUrl: "/REACT-PIZZA/PizzaImg/image33.png",
    title: "Креветки по-азиатски",
    price: "290",
    types:[0,1],
    sizes: [26, 30, 40],
    category: 6,
  },
  {
    id: 8,
    imageUrl: "/REACT-PIZZA/PizzaImg/image44.png",
    title: "Сырный цыпленок",
    price: "385",
    types:[0,1],
    sizes: [26, 30, 40],
    category: 7,
  },
];
export default list;
